import "./globals.css";
import { Inter } from "next/font/google"
import { Toaster } from "@/components/ui/toaster";
import StoreProvider from "@/redux/AuthProvider";
const inter = Inter({subsets:["latin"]});
import { configDotenv } from "dotenv";
import NavBar from "@/components/NavBar";
import NavBarWrapper from "./NavBarWrapper";
import Sidebar from "@/components/dashboard/Sidebar";
configDotenv();

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <StoreProvider>
        <NavBarWrapper />
          {/* <NavBar/> */}
          {children}
          <Toaster/>  
        </StoreProvider>
      </body>
    </html>
  );
}
